# Server Settings
server:
  port: 9050

#Logging Settings
#logging:
#  level:
#    [org.hibernate.SQL: DEBUG]
#    [org.hibernate.type: TRACE]
    
logging:
  level: DEBUG

# Database Settings
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/pet_clinic_db
    url: jdbc:mysql://db-container:3306/pet_clinic_db
    username: root
    password: root1
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format-sql: true
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
